### ISSUE TITLE
Use Unapply trick on folds.

### ISSUE THREAD

**Issue by sellout** [slamdata/matryoshka#11]
Because things like `Cofree` are shaped like `[?[_], A]` rather than just `[?[_]]` we end up needing to annotate folds like

``` scala
p.cata[Cofree[ProfF, Unit]](Cofree((), _))
```

however, we might be able to create something like `cataU` (analogous to `traverseU`) that allows us to avoid the type annotation.

**Comment by sellout** [comment]
@tpolecat will probably take a look at this.

**Comment by jdegoes** [comment]
:+1:

**Comment by sellout** [comment]
1. we don’t represent folds over Cofree that way any more and
2. we recommend using some fix for SI-2712 rather than providing Unapply-like workarounds.
