### ISSUE TITLE
Are there any plans of providing a cats version of matryoshka?

### ISSUE THREAD

**Issue by boggle** [slamdata/matryoshka#74]
This would make it easier to depend on it from a project I'm working on where bringing in scalaz as a dependency is a point of contention.

**Comment by sellout** [comment]
Yes, I’m hoping to have this done soon. But thanks for opening the issue to track this.

**Comment by boggle** [comment]
Great, sorry to push this but do you have any approximate ETA on that?

**Comment by sellout** [comment]
I don’t know if you’ve seen https://http4s.github.io/fp-ecosystem/, but it at least provides a statement of intent. The specific case of Matryoshka has a few steps.

- add some additional functionality to Cats,
- port Monocle to Cats (which also needs some additional stuff added to Cats), and
- finally port Matryoshka to Cats.

Most of this is already underway in parallel to some extent. I’d _like_ to say that it’ll be done this week, but that is probably a bit overzealous with PRs having to get reviewed and merged along the way (and needing to accomplish other things myself).

**Comment by boggle** [comment]
Yes, I saw that and I thought it was great that you stepped up on this issue which has (at least me) been scratching my head in terms of where the wider ecosystem is going.

Thanks for getting back, looking forward to trying this out once it arrives.

Cheers!

**Comment by sellout** [comment]
See julien-truffaut/Monocle#419 for the Monocle work required to make this happen.

**Comment by rkrzewski** [comment]
FWIW Monocle 1.5.0-cats-M1 is out, but recent developments in ScalaZ/Cats rivalry make me wonder if this issue has merit any longer.

**Comment by fsvehla** [comment]
@rkrzewski Can you explain? I’m out of the loop.

**Comment by rkrzewski** [comment]
@jdegoes (and SlamData, I presume) are now putting their weight behind ScalaZ and distancing themselves from Cats/Typelevel. In this circumstances, it seems unlikely that they would be willing to shoulder the additional burden of dual ScalaZ/Cats build of Matryoshka.
Of course this is only my view of the situation, and I'd be happy to be proven wrong.

**Comment by jdegoes** [comment]
@rkrzewski @fsvehla We won't be producing a Cats version, but we'd be happy to host a repo for a Cats bridge (e.g. matroyshka-cats).
