### ISSUE TITLE
matryoshka-core jvm artifact has Scala.js dependencies

### ISSUE THREAD

**Issue by gerferra** [slamdata/matryoshka#75]
Having a dependency on `"com.slamdata" %% "matryoshka-core"  % "0.18.0"` brings the Scala.js version of `monocle-core`, `scalaz-core` and `simulacrum`.

This creates problems, for example, if you depend on a binary-compatible but different version of scalaz, you will have both on the classpath because sbt can't evict one of them as the artifact names are different. Also sbt-assembly will fail on merge because duplicated .class files are not equals.

**Comment by sellout** [comment]
I wonder when this broke. Quasar is still depending on 0.16.4, so presumably that works. My guess is 0.16.10, since that’s when we switched how we manage dependencies.

**Comment by sellout** [comment]
Oh, also, which version of scalac are you using, 2.11 or 2.12?

**Comment by gerferra** [comment]
Scala 2.11

**Comment by sellout** [comment]
@gerferra Ok, we’re trying to sort this out and have a _guess_ as to what happened, but if you want something ASAP, hopefully 0.16.5 will work for you. (That’s the last version we published before 0.16.10 which simultaneously enabled auto-releasing and probably broke the js dependencies.)

**Comment by sellout** [comment]
0.18.2 should be available on sonatype in ~10 minutes.

**Comment by gerferra** [comment]
Great 😀 Thanks!
